ALTER TABLE obra
    DROP COLUMN IF EXISTS art,
    DROP COLUMN IF EXISTS cliente_id,
    DROP COLUMN IF EXISTS responsavel_id,
    DROP COLUMN IF EXISTS parceiro_id,
    DROP COLUMN IF EXISTS data_inicio,
    DROP COLUMN IF EXISTS data_previsao_termino,
    DROP COLUMN IF EXISTS data_termino_real,
    DROP COLUMN IF EXISTS orcamento_inicial,
    DROP COLUMN IF EXISTS valor_total,
    DROP COLUMN IF EXISTS valor_aditivo,
    DROP COLUMN IF NOT EXISTS custo_mao_obra,
    DROP COLUMN IF EXISTS despesas_gerais,
    DROP COLUMN IF EXISTS lucro,
    DROP COLUMN IF EXISTS status,
    DROP COLUMN IF EXISTS endereco_rua,
    DROP COLUMN IF EXISTS endereco_numero,
    DROP COLUMN IF EXISTS endereco_complemento,
    DROP COLUMN IF EXISTS endereco_bairro,
    DROP COLUMN IF EXISTS endereco_cidade,
    DROP COLUMN IF EXISTS endereco_estado,
    DROP COLUMN IF EXISTS endereco_cep;
